### ISSUE TITLE
about rest api

### ISSUE THREAD

**Issue by leoWu93** [skyvers/skyve#99]
I refer to [skyve-cookbook](https://github.com/skyvers/skyve-cookbook#understanding-skyve-restl)
 for rest API development,Below I show some process。
![image](https://github.com/skyvers/skyve/assets/99789562/db828e12-64f3-4f3c-8930-c23d42f68d9e)

Using the browser to get contacts will display the following error（My project name is 'skyveSqlServer'）

![image](https://github.com/skyvers/skyve/assets/99789562/4980c171-9d06-48f0-a394-f509035ca9b8)

Do I need to do some other configuration to fix this problem?

**Comment by leoWu93** [comment]
@benpetito ok thanks for your answer

**Comment by benpetito** [comment]
Hi @leoWu93,

apologies for the issues you ran into. We looked into it and it looks like the REST endpoint moved slightly and the documentation was not updated. I have updated the paths in the Skyve Cookbook to reflect the new endpoint. It was moved so that Skyve content could be accessed underneath `/rest` as well.

The new path is now `http://localhost:8080/<projectName>/rest/api/json/` instead of `http://localhost:8080/<projectName>/rest/json/`.
